# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RoadGeometryAnalyzer
                                 A QGIS plugin
 Estimate basic road segment geometry (curve/straight) for road safety analysis.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-07-07
        copyright            : (C) 2025 by Hamid Madani
        email                : madany.hamid@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Hamid Madani'
__date__ = '2025-07-07'
__copyright__ = '(C) 2025 by Hamid Madani'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RoadGeometryAnalyzer class from file RoadGeometryAnalyzer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .road_geometry_analyzer import RoadGeometryAnalyzerPlugin
    return RoadGeometryAnalyzerPlugin()
